### ISSUE TITLE
Undefined variable $relativePath

### ISSUE THREAD

**Issue by mrpd-code** [stimulsoft/Stimulsoft.Reports.PHP#6]
Hello, 
I wanted to bring to your attention that there is a bug in versions **2024.2.1** and **2024.2.2** for Laravel. 
in designer.blade.php : 
```php
 <?php
        $js = new \Stimulsoft\StiJavaScript(\Stimulsoft\StiComponentType::Designer);
        $js->renderHtml();
    ?>
```
The error message states: "**Undefined variable $relativePath**." 
However, version **2024.1.4** works perfectly fine on Laravel. 
Thank you for your attention to this matter. Best regards.

**Comment by VladimirHot** [comment]
Hello,

Thanks for the bug report, the error has been fixed, it will be available in 2024.2.3 version.
Now the fix is available on the dev-master version.

https://packagist.org/packages/stimulsoft/reports-php#dev-master
