### ISSUE TITLE
MySQL SSL connection support

### ISSUE THREAD

**Issue by darrylhein** [stimulsoft/Stimulsoft.Reports.PHP#8]
We need the ability to connect to MySQL with SSL. Right now we have to change the `StiMySqlAdapter` class, which of course isn't ideal as new deploys overwrite it and any updates that come from Stimulsoft over overwrite it as well.

I think the ideal would be able to add our own data adaptor. I see other versions of your libraries support this (https://www.stimulsoft.com/en/samples/reports-net/net-framework/using-a-custom-data-adapter), but I can't find instructions for PHP or a way to do this in the code. (But I'd be happy if I'm missing something.)

Another option would to have the option to pass in a PDO or mysqli connection, though a custom data adaptor could also do this.

Alternatively, if the MySQL data adaptor supported SSL, that'd also be awesome, but I realize that would require adding a lot of other params/etc.

Here's an example of how to connect to MySQL using SSL:
```
$this->connectionLink = mysqli_init();

mysqli_ssl_set($this->connectionLink, null, null, "./cert.crt.pem", null, null);

mysqli_real_connect($this->connectionLink, $this->connectionInfo->host, $this->connectionInfo->userId, $this->connectionInfo->password,  $this->connectionInfo->database, $this->connectionInfo->port, NULL, MYSQLI_CLIENT_SSL);
```

**Comment by VladimirHot** [comment]
Hello,

We understand the problem, and we will try to solve it and integrate SSL connection into the product as an option.

Thank you.

**Comment by VladimirHot** [comment]
Hello,

We have added a new event `onDatabaseConnect`, it will be called before connecting to the database. You can pass the link of the created connection in the event arguments:

```
$handler->onDatabaseConnect = function (StiConnectionEventArgs $args)
{
    $args->link = mysqli_init();
    mysqli_ssl_set($args->link, null, null, "./cert.crt.pem", null, null);
    $args->link = mysqli_real_connect(
        $args->link, $args->info->host, $args->info->userId, $args->info->password,
        $args->info->database, $args->info->port, NULL, MYSQLI_CLIENT_SSL);
};
```

The event will be available with a major PHP product update planned for the near future (July 2024). Now we are in the testing and documentation updating stage. News about this will be posted on the website soon.

Examples and fresh scripts can be found here (branch under development):
https://github.com/stimulsoft/Samples-Reports.PHP/tree/major
